# Generated by Django 4.0.1 on 2022-01-11 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weaponry', models.CharField(choices=[('S', 'Sword'), ('G', 'Gun'), ('H', 'Hand-to-Hand')], default='S', max_length=1)),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.star')),
            ],
        ),
    ]
