# Generated by Django 4.0.1 on 2022-01-14 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_weapon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combat_Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='star',
            name='combat_style',
            field=models.ManyToManyField(to='main_app.Combat_Style'),
        ),
    ]
