# Generated by Django 4.0.1 on 2022-01-14 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_combat_style_star_combat_style'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Combat_Style',
            new_name='Vehicle',
        ),
        migrations.RemoveField(
            model_name='star',
            name='combat_style',
        ),
        migrations.AddField(
            model_name='star',
            name='vehicle',
            field=models.ManyToManyField(to='main_app.Vehicle'),
        ),
    ]
