# Generated by Django 4.0.1 on 2022-01-17 23:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_vehicle_star_vehicles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weapon',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='weapon',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Mission Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weapon',
            name='weaponry',
            field=models.CharField(choices=[('S', 'Sword'), ('G', 'Gun'), ('H', 'Hand-to-Hand')], default='S', max_length=1, verbose_name='Weaponry Period'),
        ),
    ]
